### ISSUE TITLE
Got a 500 error in use

### ISSUE THREAD

**Issue by ShadowySpirits** [forrestchang/readpilot#11]
I got a 500 error when I tried to analyze this article: https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying. Is this article too long to process?

**Comment by forrestchang** [comment]
It's caused by the rate limitation of OpenAI API. We're doing a big refactoring these days and will add a load balancer for the API calls. Hopefully, we will launch this week.

**Comment by ShadowySpirits** [comment]
> It's caused by the rate limitation of OpenAI API. We're doing a big refactoring these days and will add a load balancer for the API calls. Hopefully, we will launch this week.

Looking forward to this update.

**Comment by forrestchang** [comment]
Already fixed.

**Comment by israelg99** [comment]
@forrestchang still returns 500 `POST https://readpilot.vercel.app/api/analyze 500`

**Comment by asa133** [comment]
![image](https://user-images.githubusercontent.com/85801933/219617679-220b410d-e04e-4a31-88fc-395a2e92de7b.png)
